import Layout from '@/components/Layout'
import Head from 'next/head'
import Image from 'next/image'
import ProfilePic from "../../public/images/profile/developer-pic-1.png";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        
      </Head>
      <main className='flex items-center text-dark w-full min-h-screen'>
        <Layout className='pt-0'>
          <div className="flex items-center justify-between w-full">
            <div className='w-1/2'>
              <Image src={ProfilePic} alt="KennedyLeocadio" className='w-full h-auto' />
            </div>
            <div className='w-1/2'>
              <h1>Transformando a visão em realidade com código e design.</h1>
              <p>
                Como um habilidoso desenvolvedor full-stack, dedico-me a transformar ideias em aplicações web inovadoras.
                Explore meus projetos e artigos mais recentes, mostrando minha experiência em React.js e desenvolvimento web.
              </p>
            </div>
          </div>
        </Layout>
      </main>
    </>
  )
}
